TibcoCarRentals/Models/CarBooking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TibcoCarRentals.Models
{
    public class CarBooking
    {
        [Key]
        public int BookingID { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "The Start Date field is required.")]
        [DisplayName("Start Date")]
        public DateTime StartDate { get; set; }
        [Required(ErrorMessage = "The Finish Date field is required.")]
        [DisplayName("Finish Date")]
        [DataType(DataType.Date)]
        public DateTime FinishDate { get; set; }
        // Hidden Attributes
        public bool BookingConfirmed { get; set; }
        public bool BookingCompleted { get; set; }
        public string UserID { get; set; }
		public int CarID { get; set; }
        public Car Car { get; set; }
    }
}

TibcoCarRentals/Controllers/CarBookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TibcoCarRentals.Data;
using TibcoCarRentals.Models;

namespace TibcoCarRentals.Controllers
{
    public class CarBookingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CarBookingsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: CarBookings
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                var applicationDbContext = _context.CarBooking.Include(c => c.Car);
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var applicationDbContext = _context.CarBooking.Include(c => c.Car).Where(b => b.UserID == _userManager.GetUserId(User)).Where(b => b.BookingConfirmed == true).Where(b => b.BookingCompleted == false);
                return View(await applicationDbContext.ToListAsync());
            }
        }

        // GET: CarBookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carBooking = await _context.CarBooking
                .Include(c => c.Car)
                .FirstOrDefaultAsync(m => m.BookingID == id);

            if (carBooking == null)
            {
                return NotFound();
            }
            if (_userManager.GetUserId(User) != carBooking.UserID && !User.IsInRole("Admin"))
            {
                return new RedirectResult("/Identity/Account/AccessDenied");
            }
            return View(carBooking);
        }

        public async Task<IActionResult> ConfirmBooking(int? id)
        {
            var carBooking = await _context.CarBooking.FindAsync(id);
            if (_userManager.GetUserId(User) != carBooking.UserID && !User.IsInRole("Admin"))
            {
                return new RedirectResult("/Identity/Account/AccessDenied");
            }
            var car = await _context.Car.FindAsync(carBooking.CarID);
            car.Quantity -= 1;
            carBooking.BookingConfirmed = true;

            _context.Update(car);
            _context.Update(carBooking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Booked(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carBooking = await _context.CarBooking
                .Include(c => c.Car)
                .FirstOrDefaultAsync(m => m.BookingID == id);

            if (carBooking == null)
            {
                return NotFound();
            }
            if (_userManager.GetUserId(User) != carBooking.UserID && !User.IsInRole("Admin"))
            {
                return new RedirectResult("/Identity/Account/AccessDenied");
            }
            DateTime date1 = carBooking.StartDate;
            DateTime date2 = carBooking.FinishDate;
            int days = ((TimeSpan)(date2 - date1)).Days + 1;
            ViewData["DaysTaken"] = days;
            ViewData["CarDailyPrice"] = days * carBooking.Car.DailyPrice;
            return View(carBooking);
        }

        // GET: CarBookings/Create
        [Authorize]
        public async Task<IActionResult> Create(int id)
        {
            var car = await _context.Car.FindAsync(id);
            if (car == null)
            {
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarID"] = id;
            ViewData["CarModel"] = car.Model;
            ViewData["CarYear"] = car.Year;
            ViewData["CarDailyPrice"] = car.DailyPrice;
            ViewData["CarNumSeats"] = car.NumSeats;
            ViewData["CarImage"] = car.ImageLocation;
            return View();
        }

        // POST: CarBookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingID,StartDate,FinishDate,DaysTaken,UserID,CarID,TotalPrice")] CarBooking carBooking)
        {
            if (ModelState.IsValid)
            {
                //DateTime date1 = carBooking.StartDate;
                //DateTime date2 = carBooking.FinishDate;
                //int daysDiff = ((TimeSpan)(date2 - date1)).Days;
                //ViewData["DaysTaken"] = daysDiff;

                carBooking.BookingConfirmed = false;
                _context.Add(carBooking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Booked), new { id = carBooking.BookingID });
            }
            ViewData["CarID"] = new SelectList(_context.Car, "CarID", "CarID", carBooking.CarID);
            //return View(carBooking, carBooking.CarID));
            return RedirectToAction(nameof(Create), new { id = carBooking.CarID });
        }

        // GET: CarBookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carBooking = await _context.CarBooking.FindAsync(id);

            if (carBooking == null)
            {
                return NotFound();
            }
            if (_userManager.GetUserId(User) != carBooking.UserID && !User.IsInRole("Admin"))
            {
                return new RedirectResult("/Identity/Account/AccessDenied");
            }
            ViewData["CarID"] = carBooking.CarID;
            return View(carBooking);
        }

        // POST: CarBookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingID,StartDate,FinishDate,DaysTaken,UserID,CarID,TotalPrice")] CarBooking carBooking)
        {

            if (id != carBooking.BookingID)
            {
                return NotFound();
            }
            if (_userManager.GetUserId(User) != carBooking.UserID && !User.IsInRole("Admin"))
            {
                return new RedirectResult("/Identity/Account/AccessDenied");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    carBooking.BookingConfirmed = true;
                    _context.Update(carBooking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarBookingExists(carBooking.BookingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarID"] = carBooking.CarID;
            return View(carBooking);
        }

        // GET: CarBookings/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var carBooking = await _context.CarBooking
                .Include(c => c.Car)
                .FirstOrDefaultAsync(m => m.BookingID == id);

            if (carBooking == null)
            {
                return NotFound();
            }
            if (_userManager.GetUserId(User) != carBooking.UserID && !User.IsInRole("Admin"))
            {
                return new RedirectResult("/Identity/Account/AccessDenied");
            }
            return View(carBooking);
        }

        // POST: CarBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carBooking = await _context.CarBooking.FindAsync(id);
            if (_userManager.GetUserId(User) != carBooking.UserID && !User.IsInRole("Admin"))
            {
                return new RedirectResult("/Identity/Account/AccessDenied");
            }
            var car = await _context.Car.FindAsync(carBooking.CarID);
            car.Quantity += 1;

            _context.Update(car);
            _context.CarBooking.Remove(carBooking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarBookingExists(int id)
        {
            return _context.CarBooking.Any(e => e.BookingID == id);
        }
    }
}

TibcoCarRentals/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TibcoCarRentals.Data;
using TibcoCarRentals.Models;

namespace TibcoCarRentals.Controllers
{
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment he;

        public CarsController(ApplicationDbContext context, IHostingEnvironment e)
        {
            _context = context;
            he = e;

        }

        // GET: Cars
        public async Task<IActionResult> Index(string carModel, string searchYear, string searchPrice, string searchSeats)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Car
                                            orderby m.Model
                                            select m.Model;

            var cars = from m in _context.Car
                         select m;

            if (!string.IsNullOrEmpty(searchYear))
            {
                cars = cars.Where(s => s.Year.Equals(int.Parse(searchYear)));
            }

            if (!string.IsNullOrEmpty(searchPrice))
            {
                cars = cars.Where(s => s.DailyPrice.Equals(int.Parse(searchPrice)));
            }

            if (!string.IsNullOrEmpty(searchSeats))
            {
                cars = cars.Where(s => s.NumSeats.Equals(int.Parse(searchSeats)));
            }

            if (!string.IsNullOrEmpty(carModel))
            {
                cars = cars.Where(x => x.Model == carModel);
            }
            cars = cars.Where(x => x.Quantity > 0);
            var carModelVM = new CarModelViewModel
            {
                Models = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Cars = await cars.ToListAsync()
            };

            return View(carModelVM);
        }

        public async Task<IActionResult> ClearSearch()
        {
            return RedirectToAction(nameof(Index));
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.CarID == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        [Authorize(Roles ="Admin")]
        // GET: Cars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarID,Model,Year,DailyPrice,NumSeats,Warrent,Registration,ImageLocation")] Car car, IFormFile picture)
        {
            car.ImageLocation = "/images/car/unavailable.jpg";
            if (picture != null)
            {
                car.ImageLocation = "/images/car/" + Path.GetFileName(picture.FileName);
                var fileName = Path.Combine(he.WebRootPath + "/images/car/", Path.GetFileName(picture.FileName));
                picture.CopyTo(new FileStream(fileName, FileMode.Create));
                //ViewData["fileLocation"] = "/images/event/" + Path.GetFileName(pic.FileName);
            }
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            if (car.ImageLocation != null)
            {
                ViewData["fileLocation"] = car.ImageLocation;
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarID,Model,Year,DailyPrice,NumSeats,Warrent,Registration,ImageLocation")] Car car, IFormFile picture)
        {
            if (picture != null)
            {
                car.ImageLocation = "/images/car/" + Path.GetFileName(picture.FileName);
                var fileName = Path.Combine(he.WebRootPath + "/images/car/", Path.GetFileName(picture.FileName));
                picture.CopyTo(new FileStream(fileName, FileMode.Create));
                ViewData["fileLocation"] = "/images/car/" + Path.GetFileName(picture.FileName);
            }
            if (id != car.CarID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.CarID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.CarID == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Car.FindAsync(id);
            _context.Car.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Car.Any(e => e.CarID == id);
        }
    }
}

TibcoCarRentals/Views/CarBookings/Booked.cshtml
@model TibcoCarRentals.Models.CarBooking

@{
    ViewData["Title"] = "Booked";
}
<section class="model-area section-gap" id="cars">
    <div class="container">
        <div class="row d-flex justify-content-center pb-40">
            <div class="col-md-12 pb-40 header-text">
                <h1 class="text-center pb-10">Confirm your booking</h1>
                <p class="text-center">
                    Pick up your car anytime between 9am to 5pm at <b>133 Tay Street, Invercargill, New Zealand</b>
                </p>
            </div>
        </div>
        <div class="active-model-carusel">
            <div class="row align-items-center single-model item">
                <div class="col-lg-6 model-left">
                    <div class="title justify-content-between d-flex">
                        <h2>$@ViewData["CarDailyPrice"]<span>/Total</span></h2>
                    </div>
                    <p>
                        Year: @Html.DisplayFor(model => model.Car.Year)
                        <br>
                        Number of Seats: @Html.DisplayFor(model => model.Car.NumSeats)
                        <br>
                        Days Taken: @ViewData["DaysTaken"]
                        <br>
                        @Html.DisplayNameFor(model => model.FinishDate): @Html.DisplayFor(model => model.FinishDate)
                        <br>
                        @Html.DisplayNameFor(model => model.StartDate): @Html.DisplayFor(model => model.StartDate)
                    </p>
                    <h3>
                       Are you sure you want to book this car?
                    </h3>
                    <a onClick="ConfirmBooking();" class="btn btn-default btn-lg btn-block text-center text-uppercase primary-btn" asp-controller="CarBookings" asp-action="ConfirmBooking" asp-route-id="@Model.BookingID">Confirm Booking</a>

                    @*<button asp-controller="CarBooking" asp-action="Edit" asp-route-id="@Model.BookingID" class="btn btn-default btn-lg btn-block text-center text-uppercase primary-btn">Edit Booking</button>*@
                </div>
                <div class="col-lg-6 model-right">
                    <img src="@Html.DisplayFor(model => model.Car.ImageLocation)" class="singleImage img-fluid" />
                </div>
            </div>
        </div>
    </div>
</section>





@*<div>
        <h2>You have just booked a car from Tibco Car Rentals!</h2>
        <h4>CarBooking</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FinishDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.FinishDate)
            </dd>
            <dt>
                Days Taken
            </dt>
            <dd>
                @ViewData["DaysTaken"]
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Car)
            </dt>
            <dd>
                <img src="@Html.DisplayFor(model => model.Car.ImageLocation)" class="carImage" />
            </dd>
        </dl>
    </div>
    <div>
        <button asp-action="Edit" asp-route-id="@Model.BookingID" value="Edit Booking" class="btn btn-default btn-lg text-center text-uppercase primary-btn">Edit Booking</button>
        <button asp-action="Index" asp-route-id="@Model.BookingID" value="Go to all bookings" class="btn btn-default btn-lg text-center text-uppercase primary-btn">Go to all bookings</button>

        @*<a asp-action="Edit" asp-route-id="@Model.BookingID">Edit Booking</a> |
            <a asp-action="Index">Go to all bookings</a>
    </div>*@

TibcoCarRentals/Views/CarBookings/Create.cshtml
@*@using Microsoft.AspNetCore.Identity

    @inject SignInManager<IdentityUser> SignInManager
    @inject UserManager<IdentityUser> UserManager
    @model TibcoCarRentals.Models.CarBooking

    @{
        ViewData["Title"] = "Create";
    }

    <h2>Create</h2>
    <h4>CarBooking</h4>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FinishDate" class="control-label"></label>
                    <input asp-for="FinishDate" class="form-control" />
                    <span asp-validation-for="FinishDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="UserID" value="@UserManager.GetUserId(User)" class="form-control" type="hidden" />
                    <span asp-validation-for="UserID" class="text-danger"></span>

                    <input asp-for="CarID" class="form-control" value="@ViewData["CarID"]" type="hidden" />
                    @*<select asp-for="CarID" class ="form-control" asp-items="ViewBag.CarID"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <hr />


    <div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model TibcoCarRentals.Models.CarBooking

@{
    ViewData["Title"] = "Create";
}

<section class="model-area section-gap" id="cars">
    <div class="container">
        <div class="row d-flex justify-content-center pb-40">
            <div class="col-md-12 pb-40 header-text">
                <h1 class="text-center pb-10">Choose your booking dates</h1>
                <p class="text-center">
                    Payment will be done in store when your pick up your vehicle at <b>133 Tay Street, Invercargill, New Zealand</b>
                </p>
            </div>
        </div>
        <div class="active-model-carusel">
            <div class="row align-items-center single-model item">
                <div class="col-lg-6 model-left">
                    <div class="title justify-content-between d-flex">
                        <h2>$@ViewData["CarDailyPrice"]<span>/day</span></h2>
                    </div>
                    <p>
                        Model: @ViewData["CarModel"]
                        <br>
                        Year: @ViewData["CarYear"]
                        <br>
                        Number of Seats: @ViewData["CarNumSeats"]
                    </p>
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="StartDate" class="control-label"></label>
                            <input asp-for="StartDate" class="form-control" />
                            <span asp-validation-for="StartDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FinishDate" class="control-label"></label>
                            <input asp-for="FinishDate" class="form-control" />
                            <span asp-validation-for="FinishDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input asp-for="UserID" value="@UserManager.GetUserId(User)" class="form-control" type="hidden" />
                            <span asp-validation-for="UserID" class="text-danger"></span>

                            <input asp-for="CarID" class="form-control" value="@ViewData["CarID"]" type="hidden" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Book This Car Now" name="Browse" class="btn btn-default btn-lg btn-block text-center text-uppercase primary-btn" />
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 model-right">
                    <img src="@ViewData["CarImage"]" class="singleImage img-fluid" />
                </div>
            </div>
        </div>
    </div>
</section>

TibcoCarRentals/Views/CarBookings/Delete.cshtml
@model TibcoCarRentals.Models.CarBooking

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarBooking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt>
           Days Taken
        </dt>
        <dd>
            @ViewData["DaysTaken"]
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd>
            <img src="@Html.DisplayFor(model => model.Car.ImageLocation)" class="singleImage" />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BookingID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TibcoCarRentals/Views/CarBookings/Index.cshtml
@model IEnumerable<TibcoCarRentals.Models.CarBooking>

@{
    ViewData["Title"] = "Index";
}

<!-- start banner Area -->
<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    @if (User.IsInRole("Admin"))
                    {
                        <i>Manage</i>
                    }
                    Car Bookings
                </h1>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->
@if (User.IsInRole("Admin"))
{
    <p>
        <a class="btn btn-default btn-lg  text-center text-uppercase" asp-action="Create">Create New</a>
    </p>
}
<a class="text-uppercase primary-btn" asp-controller="BusBookings" asp-action="Index">Go to Bus Bookings</a>
<a class="text-uppercase primary-btn right" asp-controller="Cars" asp-action="Index">Booking Another Car</a>
<table class="table">
    <thead>
        <tr>
            @if (!User.IsInRole("Admin"))
            {
                <th></th>
            }
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FinishDate)
            </th>
            <th>
                Days Taken
            </th>
            <th>
                Price
            </th>
            @if (User.IsInRole("Admin"))
            {
                <th>
                    @Html.DisplayNameFor(model => model.Car.Warrent)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Car.Registration)
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @if (!User.IsInRole("Admin"))
                {
                    <td>
                        <img src="@Html.DisplayFor(modelItem => item.Car.ImageLocation)" class="carImage bookingImage" />
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FinishDate)
                </td>
                <td>
                    @{
                        DateTime date1 = item.StartDate;
                        DateTime date2 = item.FinishDate;
                        int days = ((TimeSpan)(date2 - date1)).Days + 1;
                    }
                    @days
                </td>
                <td>
                    @{
                        double price = @item.Car.DailyPrice * days;
                    }
                    @price
                </td>
                @if (User.IsInRole("Admin"))
                {
                <td>
                    @Html.DisplayFor(modelItem => item.Car.Registration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Car.Registration)
                </td>
                }
                <td>
                    <a asp-action="Edit" asp-route-id="@item.BookingID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.BookingID">Details</a>
                    @if (User.IsInRole("Admin"))
                    {
                        @: | <a asp-action="Delete" asp-route-id="@item.BookingID">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>