TibcoCarRentals/Controllers/BusBookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TibcoCarRentals.Data;
using TibcoCarRentals.Models;

namespace TibcoCarRentals.Controllers
{
    public class BusBookingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public BusBookingsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: BusBookings
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                var applicationDbContext = _context.BusBooking.Include(c => c.Bus);
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var applicationDbContext = _context.BusBooking.Include(c => c.Bus).Where(b => b.UserID == _userManager.GetUserId(User)).Where(b => b.BookingConfirmed == true).Where(b => b.BookingCompleted == false);
                return View(await applicationDbContext.ToListAsync());
            }
            //var applicationDbContext = _context.BusBooking.Include(b => b.Bus);
            //return View(await applicationDbContext.ToListAsync());
        }

        // GET: BusBookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busBooking = await _context.BusBooking
                .Include(b => b.Bus)
                .FirstOrDefaultAsync(m => m.BusBookingID == id);
            if (busBooking == null)
            {
                return NotFound();
            }

            return View(busBooking);
        }

        // GET: BusBookings/Create
        public async Task<IActionResult> ConfirmBooking(int? id)
        {
            var busBooking = await _context.BusBooking.FindAsync(id);
            var bus = await _context.Bus.FindAsync(busBooking.BusID);
            bus.Quantity -= 1;
            //busBooking.BookingConfirmed = true;

            _context.Update(bus);
            _context.Update(busBooking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Booked(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busBooking = await _context.BusBooking
                .Include(c => c.Bus)
                .FirstOrDefaultAsync(m => m.BusBookingID == id);
            if (busBooking == null)
            {
                return NotFound();
            }

            return View(busBooking);
        }

        public async Task<IActionResult> Create(int id)
        {
            var bus = await _context.Bus.FindAsync(id);
            ViewData["BusID"] = id;
            ViewData["BusModel"] = bus.Model;
            ViewData["BusYear"] = bus.Year;
            ViewData["BusDailyPrice"] = bus.DailyPrice;
            ViewData["BusNumSeats"] = bus.NumSeats;
            ViewData["BusImage"] = bus.ImageLocation;
            return View();
        }

        // POST: BusBookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BusBookingID,NumOfGuest,DateToBook,SpecialRequirement,UserID,BusID")] BusBooking busBooking)
        {
            if (ModelState.IsValid)
            {
                busBooking.BookingConfirmed = false;
                _context.Add(busBooking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Booked), new { id = busBooking.BusBookingID });
            }
            ViewData["BusID"] = new SelectList(_context.Bus, "BusID", "BusID", busBooking.BusID);
            return View(busBooking);
        }

        // GET: BusBookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busBooking = await _context.BusBooking.FindAsync(id);
            if (busBooking == null)
            {
                return NotFound();
            }
            ViewData["BusID"] = new SelectList(_context.Bus, "BusID", "BusID", busBooking.BusID);
            return View(busBooking);
        }

        // POST: BusBookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BusBookingID,NumOfGuest,DateToBook,SpecialRequirement,UserID,BusID")] BusBooking busBooking)
        {
            if (id != busBooking.BusBookingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(busBooking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BusBookingExists(busBooking.BusBookingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BusID"] = new SelectList(_context.Bus, "BusID", "BusID", busBooking.BusID);
            return View(busBooking);
        }

        // GET: BusBookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busBooking = await _context.BusBooking
                .Include(b => b.Bus)
                .FirstOrDefaultAsync(m => m.BusBookingID == id);
            if (busBooking == null)
            {
                return NotFound();
            }

            return View(busBooking);
        }

        // POST: BusBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var busBooking = await _context.BusBooking.FindAsync(id);
            var bus = await _context.Car.FindAsync(busBooking.BusID);
            bus.Quantity += 1;

            _context.Update(bus);
            _context.BusBooking.Remove(busBooking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BusBookingExists(int id)
        {
            return _context.BusBooking.Any(e => e.BusBookingID == id);
        }
    }
}

TibcoCarRentals/Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TibcoCarRentals.Data;
using TibcoCarRentals.Models;

namespace TibcoCarRentals.Controllers
{
    public class BusesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BusesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Buses
        public async Task<IActionResult> Index(string busModel, string searchYear, string searchPrice, string searchSeats)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Bus
                                            orderby m.Model
                                            select m.Model;

            var buses = from m in _context.Bus
                       select m;
            buses = buses.Where(x => x.Quantity > 0);
            if (!string.IsNullOrEmpty(searchYear))
            {
                buses = buses.Where(s => s.Year.Equals(int.Parse(searchYear)));
            }

            if (!string.IsNullOrEmpty(searchPrice))
            {
                buses = buses.Where(s => s.DailyPrice.Equals(int.Parse(searchPrice)));
            }

            if (!string.IsNullOrEmpty(searchSeats))
            {
                buses = buses.Where(s => s.NumSeats.Equals(int.Parse(searchSeats)));
            }

            if (!string.IsNullOrEmpty(busModel))
            {
                buses = buses.Where(x => x.Model == busModel);
            }

            var busModelVM = new BusViewModel
            {
                Models = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Buses = await buses.ToListAsync()
            };

            return View(busModelVM);
        }

        // GET: Buses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bus = await _context.Bus
                .FirstOrDefaultAsync(m => m.BusID == id);
            if (bus == null)
            {
                return NotFound();
            }

            return View(bus);
        }

        // GET: Buses/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Buses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BusID,Year,DailyPrice,Model,NumSeats,Warrent,Registration,ImageLocation")] Bus bus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bus);
        }

        // GET: Buses/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bus = await _context.Bus.FindAsync(id);
            if (bus == null)
            {
                return NotFound();
            }
            return View(bus);
        }

        // POST: Buses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BusID,Year,DailyPrice,Model,NumSeats,Warrent,Registration,ImageLocation")] Bus bus)
        {
            if (id != bus.BusID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BusExists(bus.BusID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bus);
        }

        // GET: Buses/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bus = await _context.Bus
                .FirstOrDefaultAsync(m => m.BusID == id);
            if (bus == null)
            {
                return NotFound();
            }

            return View(bus);
        }

        // POST: Buses/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bus = await _context.Bus.FindAsync(id);
            _context.Bus.Remove(bus);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BusExists(int id)
        {
            return _context.Bus.Any(e => e.BusID == id);
        }
    }
}

TibcoCarRentals/Views/Buses/Create.cshtml
@model TibcoCarRentals.Models.Bus

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Bus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DailyPrice" class="control-label"></label>
                <input asp-for="DailyPrice" class="form-control" />
                <span asp-validation-for="DailyPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumSeats" class="control-label"></label>
                <input asp-for="NumSeats" class="form-control" />
                <span asp-validation-for="NumSeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Warrent" class="control-label"></label>
                <input asp-for="Warrent" class="form-control" />
                <span asp-validation-for="Warrent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Registration" class="control-label"></label>
                <input asp-for="Registration" class="form-control" />
                <span asp-validation-for="Registration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageLocation" class="control-label"></label>
                <input asp-for="ImageLocation" class="form-control" />
                <span asp-validation-for="ImageLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TibcoCarRentals/Views/Buses/Delete.cshtml
@model TibcoCarRentals.Models.Bus

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DailyPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DailyPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumSeats)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumSeats)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Warrent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Warrent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Registration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Registration)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BusID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TibcoCarRentals/Views/Buses/Details.cshtml
@model TibcoCarRentals.Models.Bus

@{
    ViewData["Title"] = "Details";
}
<section class="model-area section-gap" id="cars">
    <div class="container">
        <div class="row d-flex justify-content-center pb-40">
            <div class="col-md-12 pb-40 header-text">
                <h1 class="text-center pb-10">Choose your Desired Bus Model</h1>
                <p class="text-center">
                    Who are in extremely love with eco friendly system.
                </p>
            </div>
        </div>
        <div class="active-model-carusel">
            <div class="row align-items-center single-model item">
                <div class="col-lg-6 model-left">
                    <div class="title justify-content-between d-flex">
                        <h4 class="mt-20">@Html.DisplayFor(model => model.Model)</h4>
                        <h2>$@Html.DisplayFor(model => model.DailyPrice)<span>/day</span></h2>
                    </div>
                    <p>
                        Quality buses just for you.
                    </p>
                    <p>
                        @Html.DisplayNameFor(model => model.Year): @Html.DisplayFor(model => model.Year)
                        <br>
                        @Html.DisplayNameFor(model => model.NumSeats): @Html.DisplayFor(model => model.NumSeats)
                    </p>
                    <a asp-action="Create" asp-controller="BusBookings" asp-route-id="@Model.BusID">
                        <input type="button" value="Book This Bus Now" name="Browse" class="btn btn-default btn-lg btn-block text-center text-uppercase primary-btn" />
                    </a>
                </div>
                <div class="col-lg-6 model-right">
                    <img src="@Html.DisplayFor(model => model.ImageLocation)" class="carImage img-fluid" />
                </div>
            </div>
        </div>
    </div>
</section>

<div>
    <a asp-action="Edit" asp-route-id="@Model.BusID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TibcoCarRentals/Views/Buses/Edit.cshtml
@model TibcoCarRentals.Models.Bus

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Bus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BusID" />
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DailyPrice" class="control-label"></label>
                <input asp-for="DailyPrice" class="form-control" />
                <span asp-validation-for="DailyPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumSeats" class="control-label"></label>
                <input asp-for="NumSeats" class="form-control" />
                <span asp-validation-for="NumSeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Warrent" class="control-label"></label>
                <input asp-for="Warrent" class="form-control" />
                <span asp-validation-for="Warrent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Registration" class="control-label"></label>
                <input asp-for="Registration" class="form-control" />
                <span asp-validation-for="Registration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageLocation" class="control-label"></label>
                <input asp-for="ImageLocation" class="form-control" />
                <span asp-validation-for="ImageLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TibcoCarRentals/Views/Buses/Index.cshtml
@model TibcoCarRentals.Models.BusViewModel

@{
    ViewData["Title"] = "Index";
}

<!-- start banner Area -->
<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Buses
                </h1>
            </div>
        </div>
    </div>
</section>
@if (User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
<row>
    <div class="col-lg-4">
        <form asp-controller="Buses" asp-action="Index" method="get" class="form" role="form" autocomplete="off">
            <div class="row">
                <h2 class="text-center">Filter Buses</h2>
                <div class="default-select" id="default-select">
                    <select class="form-control filter txt-field" asp-for="BusModel" asp-items="Model.Models">
                        <option value="">All</option>
                    </select>
                </div>

                <input class="form-control filter" type="text" asp-for="SearchYear" placeholder="Year">

                <input class="form-control filter" type="text" asp-for="SearchPrice" placeholder="Daily Price">

                <input class="form-control filter" type="text" asp-for="SearchSeats" placeholder="Number of Seats">

            </div>
            <br />
            <div class="col-md-12">
                <button type="submit" value="Search" class="btn btn-default btn-lg btn-block text-center text-uppercase primary-btn">Search for Bus</button>
            </div>
        </form>
        <form asp-controller="Buses" asp-action="Index">
            <div class="col-md-12">
                <input class="btn btn-default btn-lg btn-block text-center text-uppercase primary-btn more-space" type="submit" value="Reset" />
            </div>
        </form>
    </div>
    <div class="col-lg-8">
        <div class="row align-items-center single-model item">
            @foreach (var item in Model.Buses)
            {
                <div class="col-md-12">
                    <img src="@Html.DisplayFor(modelItem => item.ImageLocation)" class="singleImage" />
                    <div class="title justify-content-between d-flex">
                        <br />
                        <h2>$@Html.DisplayFor(modelItem => item.DailyPrice)<span>/day</span></h2>
                        <div>
                            @Html.DisplayNameFor(model => model.Buses[0].Model):
                            @Html.DisplayFor(modelItem => item.Model)
                        </div>
                        <div>
                            @Html.DisplayNameFor(model => model.Buses[0].Year):
                            @Html.DisplayFor(modelItem => item.Year)
                        </div>
                        <div>
                            @Html.DisplayNameFor(model => model.Buses[0].NumSeats):
                            @Html.DisplayFor(modelItem => item.NumSeats)
                        </div>

                    </div>
                    <a asp-controller="BusBookings" asp-action="Create" asp-route-id="@item.BusID">
                        <input type="button" value="Book this Bus Now" name="Book" class="btn btn-default btn-lg btn-block text-center text-uppercase primary-btn" />
                    </a>
                </div>
            }
        </div>
    </div>
</row>
<div class="row">

</div>